// <auto-generated />
using System;
using MDFeApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MDFeApi.Migrations
{
    [DbContext(typeof(MDFeContext))]
    [Migration("20251003113606_RemoverRequiredCamposMDFe")]
    partial class RemoverRequiredCamposMDFe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MDFeApi.Models.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("MDFeApi.Models.CargoPermissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CargoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("PermissaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissaoId");

                    b.HasIndex("CargoId", "PermissaoId")
                        .IsUnique();

                    b.ToTable("CargoPermissoes");
                });

            modelBuilder.Entity("MDFeApi.Models.Condutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Condutores");
                });

            modelBuilder.Entity("MDFeApi.Models.Contratante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<int>("CodMunicipio")
                        .HasColumnType("int");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasFilter("[Cnpj] IS NOT NULL");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasFilter("[Cpf] IS NOT NULL");

                    b.ToTable("Contratantes");
                });

            modelBuilder.Entity("MDFeApi.Models.Emitente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmbienteSefaz")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CaminhoArquivoCertificado")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CaminhoSalvarXml")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<int>("CodMunicipio")
                        .HasColumnType("int");

                    b.Property<string>("Complemento")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Ie")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ModalTransporte")
                        .HasColumnType("int");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Rntrc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SenhaCertificado")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SerieInicial")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoEmitente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TipoTransportador")
                        .HasColumnType("int");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasFilter("[Cnpj] IS NOT NULL");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasFilter("[Cpf] IS NOT NULL");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("MDFeApi.Models.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoIbge")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Autorizado")
                        .HasColumnType("bit");

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<string>("CepCarregamento")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("CepDescarregamento")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("ChaveAcesso")
                        .HasMaxLength(44)
                        .HasColumnType("nvarchar(44)");

                    b.Property<string>("CnpjProprietario")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("CodigoCIOT")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodigoNumericoAleatorio")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("CodigoUf")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("CodigoVerificador")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("ComponentesPagamentoJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CondutorCpf")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int?>("CondutorId")
                        .HasColumnType("int");

                    b.Property<string>("CondutorNome")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CondutorTelefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContratanteBairro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContratanteCep")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("ContratanteCnpj")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<int?>("ContratanteCodMunicipio")
                        .HasColumnType("int");

                    b.Property<string>("ContratanteComplemento")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContratanteCpf")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("ContratanteEndereco")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ContratanteId")
                        .HasColumnType("int");

                    b.Property<string>("ContratanteIe")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContratanteMunicipio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContratanteNomeFantasia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContratanteNumero")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContratanteRazaoSocial")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContratanteUf")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("CpfProprietario")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("DadosOriginaisJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAutorizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataCancelamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEncerramento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataGeracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInicioViagem")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataTransmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoProduto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DocumentosCTeJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentosNFeJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmitenteBairro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmitenteCep")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("EmitenteCnpj")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<int?>("EmitenteCodMunicipio")
                        .HasColumnType("int");

                    b.Property<string>("EmitenteComplemento")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmitenteCpf")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("EmitenteEndereco")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EmitenteId")
                        .HasColumnType("int");

                    b.Property<string>("EmitenteIe")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmitenteMunicipio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmitenteNomeFantasia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmitenteNumero")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmitenteRazaoSocial")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmitenteRntrc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmitenteTipoEmitente")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmitenteUf")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<bool>("Encerrado")
                        .HasColumnType("bit");

                    b.Property<string>("IeProprietario")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("InfoAdicional")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("LatitudeCarregamento")
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal?>("LatitudeDescarregamento")
                        .HasColumnType("decimal(10,6)");

                    b.Property<string>("LocalidadesCarregamentoJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalidadesDescarregamentoJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("LongitudeCarregamento")
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal?>("LongitudeDescarregamento")
                        .HasColumnType("decimal(10,6)");

                    b.Property<int?>("Lote")
                        .HasColumnType("int");

                    b.Property<int>("Modal")
                        .HasColumnType("int");

                    b.Property<int?>("MunicipioCarregamentoId")
                        .HasColumnType("int");

                    b.Property<string>("MunicipioFim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MunicipioIni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeProprietario")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeroApoliceSeguro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroAverbacaoSeguro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumeroMdfe")
                        .HasColumnType("int");

                    b.Property<string>("NumeroRecibo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ObservacoesInternas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("PesoBrutoTotal")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("ProdutoPredominante")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("ProprietarioDiferente")
                        .HasColumnType("bit");

                    b.Property<string>("Protocolo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("QuantidadeCTe")
                        .HasColumnType("int");

                    b.Property<int?>("QuantidadeNFe")
                        .HasColumnType("int");

                    b.Property<string>("RntrcProprietario")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RotaPercursoJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeguradoraBairro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SeguradoraCep")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("SeguradoraCnpj")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<int?>("SeguradoraCodMunicipio")
                        .HasColumnType("int");

                    b.Property<string>("SeguradoraComplemento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SeguradoraEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SeguradoraEndereco")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SeguradoraId")
                        .HasColumnType("int");

                    b.Property<string>("SeguradoraMunicipio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SeguradoraNomeFantasia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SeguradoraNumero")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SeguradoraRazaoSocial")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SeguradoraTelefone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SeguradoraUf")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<bool>("SemValePedagio")
                        .HasColumnType("bit");

                    b.Property<int>("Serie")
                        .HasColumnType("int");

                    b.Property<string>("StatusSefaz")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoCarga")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("TipoPagamento")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("TipoResponsavelSeguro")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("TipoTransportador")
                        .HasColumnType("int");

                    b.Property<bool>("Transmitido")
                        .HasColumnType("bit");

                    b.Property<string>("UfFim")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("UfIni")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("UfProprietario")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("UsuarioCriacao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UsuarioUltimaAlteracao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ValesPedagioJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorTotalContrato")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VeiculoId")
                        .HasColumnType("int");

                    b.Property<string>("VeiculoPlaca")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int?>("VeiculoTara")
                        .HasColumnType("int");

                    b.Property<string>("VeiculoTipoCarroceria")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VeiculoTipoRodado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VeiculoUf")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("VersaoModal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("VersaoSistema")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("XmlAssinado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XmlAutorizado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XmlGerado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XmlRetorno")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChaveAcesso")
                        .IsUnique()
                        .HasFilter("[ChaveAcesso] IS NOT NULL");

                    b.HasIndex("CondutorId");

                    b.HasIndex("ContratanteId");

                    b.HasIndex("MunicipioCarregamentoId");

                    b.HasIndex("SeguradoraId");

                    b.HasIndex("VeiculoId");

                    b.HasIndex("EmitenteId", "Serie", "NumeroMdfe")
                        .IsUnique();

                    b.ToTable("MDFes");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeCondutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CpfCondutor")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("MDFeId")
                        .HasColumnType("int");

                    b.Property<string>("NomeCondutor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CpfCondutor");

                    b.HasIndex("MDFeId");

                    b.ToTable("MDFeCondutores");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeCte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChaveCte")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("nvarchar(44)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("IndReentrega")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("MDFeId")
                        .HasColumnType("int");

                    b.Property<int?>("MunicipioDescargaId")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<decimal?>("PesoBruto")
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("SegCodigoBarras")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("SegundoCodigoBarras")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("ValorTotal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ChaveCte")
                        .IsUnique();

                    b.HasIndex("MDFeId");

                    b.HasIndex("MunicipioDescargaId");

                    b.ToTable("MDFeCtes");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeEntregaParcial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoEntrega")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LocalEntrega")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MDFeCteId")
                        .HasColumnType("int");

                    b.Property<int>("MDFeId")
                        .HasColumnType("int");

                    b.Property<int?>("MDFeMdfeTranspId")
                        .HasColumnType("int");

                    b.Property<int?>("MDFeNfeId")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantidadeParcial")
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal?>("QuantidadeTotal")
                        .HasColumnType("decimal(12,4)");

                    b.HasKey("Id");

                    b.HasIndex("MDFeCteId");

                    b.HasIndex("MDFeId");

                    b.HasIndex("MDFeMdfeTranspId");

                    b.HasIndex("MDFeNfeId");

                    b.ToTable("MDFeEntregasParciais");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Justificativa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MDFeId")
                        .HasColumnType("int");

                    b.Property<string>("ProtocoloEvento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("XmlEvento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XmlRetornoEvento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MDFeId");

                    b.ToTable("MDFeEventos");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeLacreRodoviario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("MDFeId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroLacre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MDFeId");

                    b.ToTable("MDFeLacresRodoviarios");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeLacreUnidadeCarga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroLacre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<int>("UnidadeCargaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeCargaId");

                    b.ToTable("MDFeLacresUnidadeCarga");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeLacreUnidadeTransporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("MDFeId")
                        .HasColumnType("int");

                    b.Property<int?>("MDFeUnidadeTransporteId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroLacre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MDFeId");

                    b.HasIndex("MDFeUnidadeTransporteId");

                    b.ToTable("MDFeLacresUnidadeTransporte");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeLocalCarregamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescricaoMunicipio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MDFeId")
                        .HasColumnType("int");

                    b.Property<int>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MDFeId");

                    b.HasIndex("MunicipioId");

                    b.ToTable("MDFeLocaisCarregamento");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeLocalDescarregamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescricaoMunicipio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MDFeId")
                        .HasColumnType("int");

                    b.Property<int>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MDFeId");

                    b.HasIndex("MunicipioId");

                    b.ToTable("MDFeLocaisDescarregamento");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeMdfeTransp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChaveMdfeTransp")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("nvarchar(44)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("IndReentrega")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("MDFeId")
                        .HasColumnType("int");

                    b.Property<int?>("MunicipioDescargaId")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<decimal?>("QuantidadeRateada")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("ChaveMdfeTransp")
                        .IsUnique();

                    b.HasIndex("MDFeId");

                    b.HasIndex("MunicipioDescargaId");

                    b.ToTable("MDFeMdfeTransps");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeNfe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChaveNfe")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("nvarchar(44)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("IndReentrega")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("MDFeId")
                        .HasColumnType("int");

                    b.Property<int?>("MunicipioDescargaId")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<decimal?>("PesoBruto")
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("PinSuframa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SegCodigoBarras")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("SegundoCodigoBarras")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("ValorTotal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ChaveNfe")
                        .IsUnique();

                    b.HasIndex("MDFeId");

                    b.HasIndex("MunicipioDescargaId");

                    b.ToTable("MDFeNfes");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeNfePrestacaoParcial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DenominacaoMercadoria")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("NFeId")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<decimal?>("QtdeParcial")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.HasIndex("NFeId");

                    b.ToTable("MDFeNfesPrestacaoParcial");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeProdutoPerigoso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClasseRisco")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("GrupoEmbalagem")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int?>("MDFeCteId")
                        .HasColumnType("int");

                    b.Property<int>("MDFeId")
                        .HasColumnType("int");

                    b.Property<int?>("MDFeMdfeTranspId")
                        .HasColumnType("int");

                    b.Property<int?>("MDFeNfeId")
                        .HasColumnType("int");

                    b.Property<string>("NomeApropriado")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeEmbarque")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NumeroONU")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantidadeTotal")
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("QuantidadeTotalProduto")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("QuantidadeVolumoTipo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("MDFeCteId");

                    b.HasIndex("MDFeId");

                    b.HasIndex("MDFeMdfeTranspId");

                    b.HasIndex("MDFeNfeId");

                    b.ToTable("MDFeProdutosPerigosos");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeReboque", b =>
                {
                    b.Property<int>("MDFeId")
                        .HasColumnType("int");

                    b.Property<int>("ReboqueId")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("MDFeId", "ReboqueId");

                    b.HasIndex("ReboqueId");

                    b.ToTable("MDFeReboques");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeUfPercurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MDFeId")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("MDFeId");

                    b.ToTable("MDFeUfsPercurso");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeUnidadeCarga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUnidadeCarga")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MDFeId")
                        .HasColumnType("int");

                    b.Property<int?>("MDFeUnidadeTransporteId")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<decimal?>("QtdRat")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("TipoUnidadeCarga")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.HasIndex("MDFeId");

                    b.HasIndex("MDFeUnidadeTransporteId");

                    b.ToTable("MDFeUnidadesCarga");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeUnidadeTransporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CapacidadeKg")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal?>("CapacidadeM3")
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("CodigoInterno")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IdentificacaoUnidadeTransporte")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MDFeCteId")
                        .HasColumnType("int");

                    b.Property<int>("MDFeId")
                        .HasColumnType("int");

                    b.Property<int?>("MDFeMdfeTranspId")
                        .HasColumnType("int");

                    b.Property<int?>("MDFeNfeId")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("Placa")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<decimal?>("QuantidadeRateada")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal?>("Tara")
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("TipoCarroceria")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("TipoRodado")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("TipoUnidadeTransporte")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("MDFeCteId");

                    b.HasIndex("MDFeId");

                    b.HasIndex("MDFeMdfeTranspId");

                    b.HasIndex("MDFeNfeId");

                    b.ToTable("MDFeUnidadesTransporte");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeValePedagio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CnpjFornecedor")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("MDFeId")
                        .HasColumnType("int");

                    b.Property<string>("NomeFornecedor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeroCompra")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("TipoVale")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<decimal>("ValorVale")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("MDFeId");

                    b.ToTable("MDFeValesPedagio");
                });

            modelBuilder.Entity("MDFeApi.Models.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("EstadoId");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("MDFeApi.Models.Permissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Permissoes");
                });

            modelBuilder.Entity("MDFeApi.Models.Reboque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Rntrc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Tara")
                        .HasColumnType("int");

                    b.Property<string>("TipoCarroceria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoRodado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Reboques");
                });

            modelBuilder.Entity("MDFeApi.Models.Seguradora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apolice")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("Seguradoras");
                });

            modelBuilder.Entity("MDFeApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("CargoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimoLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("MDFeApi.Models.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("Tara")
                        .HasColumnType("int");

                    b.Property<string>("TipoCarroceria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoRodado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("MDFeApi.Models.CargoPermissao", b =>
                {
                    b.HasOne("MDFeApi.Models.Cargo", "Cargo")
                        .WithMany("CargoPermissoes")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MDFeApi.Models.Permissao", "Permissao")
                        .WithMany("CargoPermissoes")
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Permissao");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFe", b =>
                {
                    b.HasOne("MDFeApi.Models.Condutor", "Condutor")
                        .WithMany("MDFes")
                        .HasForeignKey("CondutorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MDFeApi.Models.Contratante", "Contratante")
                        .WithMany("MDFes")
                        .HasForeignKey("ContratanteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MDFeApi.Models.Emitente", "Emitente")
                        .WithMany("MDFes")
                        .HasForeignKey("EmitenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MDFeApi.Models.Municipio", "MunicipioCarregamento")
                        .WithMany("MDFesCarregamento")
                        .HasForeignKey("MunicipioCarregamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MDFeApi.Models.Seguradora", "Seguradora")
                        .WithMany("MDFes")
                        .HasForeignKey("SeguradoraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MDFeApi.Models.Veiculo", "Veiculo")
                        .WithMany("MDFes")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Condutor");

                    b.Navigation("Contratante");

                    b.Navigation("Emitente");

                    b.Navigation("MunicipioCarregamento");

                    b.Navigation("Seguradora");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeCondutor", b =>
                {
                    b.HasOne("MDFeApi.Models.MDFe", "MDFe")
                        .WithMany("CondutoresAdicionais")
                        .HasForeignKey("MDFeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MDFe");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeCte", b =>
                {
                    b.HasOne("MDFeApi.Models.MDFe", "MDFe")
                        .WithMany("DocumentosCte")
                        .HasForeignKey("MDFeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MDFeApi.Models.Municipio", "MunicipioDescarga")
                        .WithMany("MDFesCte")
                        .HasForeignKey("MunicipioDescargaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MDFe");

                    b.Navigation("MunicipioDescarga");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeEntregaParcial", b =>
                {
                    b.HasOne("MDFeApi.Models.MDFeCte", "MDFeCte")
                        .WithMany()
                        .HasForeignKey("MDFeCteId");

                    b.HasOne("MDFeApi.Models.MDFe", "MDFe")
                        .WithMany("EntregasParciais")
                        .HasForeignKey("MDFeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MDFeApi.Models.MDFeMdfeTransp", "MDFeMdfeTransp")
                        .WithMany()
                        .HasForeignKey("MDFeMdfeTranspId");

                    b.HasOne("MDFeApi.Models.MDFeNfe", "MDFeNfe")
                        .WithMany()
                        .HasForeignKey("MDFeNfeId");

                    b.Navigation("MDFe");

                    b.Navigation("MDFeCte");

                    b.Navigation("MDFeMdfeTransp");

                    b.Navigation("MDFeNfe");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeEvento", b =>
                {
                    b.HasOne("MDFeApi.Models.MDFe", "MDFe")
                        .WithMany("Eventos")
                        .HasForeignKey("MDFeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MDFe");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeLacreRodoviario", b =>
                {
                    b.HasOne("MDFeApi.Models.MDFe", "MDFe")
                        .WithMany("LacresRodoviarios")
                        .HasForeignKey("MDFeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MDFe");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeLacreUnidadeCarga", b =>
                {
                    b.HasOne("MDFeApi.Models.MDFeUnidadeCarga", "UnidadeCarga")
                        .WithMany("LacresUnidadeCarga")
                        .HasForeignKey("UnidadeCargaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnidadeCarga");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeLacreUnidadeTransporte", b =>
                {
                    b.HasOne("MDFeApi.Models.MDFe", "MDFe")
                        .WithMany()
                        .HasForeignKey("MDFeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MDFeApi.Models.MDFeUnidadeTransporte", null)
                        .WithMany("Lacres")
                        .HasForeignKey("MDFeUnidadeTransporteId");

                    b.Navigation("MDFe");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeLocalCarregamento", b =>
                {
                    b.HasOne("MDFeApi.Models.MDFe", "MDFe")
                        .WithMany("LocaisCarregamento")
                        .HasForeignKey("MDFeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MDFeApi.Models.Municipio", "Municipio")
                        .WithMany("LocaisCarregamento")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MDFe");

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeLocalDescarregamento", b =>
                {
                    b.HasOne("MDFeApi.Models.MDFe", "MDFe")
                        .WithMany("LocaisDescarregamento")
                        .HasForeignKey("MDFeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MDFeApi.Models.Municipio", "Municipio")
                        .WithMany("LocaisDescarregamento")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MDFe");

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeMdfeTransp", b =>
                {
                    b.HasOne("MDFeApi.Models.MDFe", "MDFe")
                        .WithMany("DocumentosMdfeTransp")
                        .HasForeignKey("MDFeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MDFeApi.Models.Municipio", "MunicipioDescarga")
                        .WithMany("MDFesMdfeTransp")
                        .HasForeignKey("MunicipioDescargaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MDFe");

                    b.Navigation("MunicipioDescarga");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeNfe", b =>
                {
                    b.HasOne("MDFeApi.Models.MDFe", "MDFe")
                        .WithMany("DocumentosNfe")
                        .HasForeignKey("MDFeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MDFeApi.Models.Municipio", "MunicipioDescarga")
                        .WithMany("MDFesNfe")
                        .HasForeignKey("MunicipioDescargaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MDFe");

                    b.Navigation("MunicipioDescarga");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeNfePrestacaoParcial", b =>
                {
                    b.HasOne("MDFeApi.Models.MDFeNfe", "NFe")
                        .WithMany()
                        .HasForeignKey("NFeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NFe");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeProdutoPerigoso", b =>
                {
                    b.HasOne("MDFeApi.Models.MDFeCte", "MDFeCte")
                        .WithMany()
                        .HasForeignKey("MDFeCteId");

                    b.HasOne("MDFeApi.Models.MDFe", "MDFe")
                        .WithMany("ProdutosPerigosos")
                        .HasForeignKey("MDFeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MDFeApi.Models.MDFeMdfeTransp", "MDFeMdfeTransp")
                        .WithMany()
                        .HasForeignKey("MDFeMdfeTranspId");

                    b.HasOne("MDFeApi.Models.MDFeNfe", "MDFeNfe")
                        .WithMany()
                        .HasForeignKey("MDFeNfeId");

                    b.Navigation("MDFe");

                    b.Navigation("MDFeCte");

                    b.Navigation("MDFeMdfeTransp");

                    b.Navigation("MDFeNfe");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeReboque", b =>
                {
                    b.HasOne("MDFeApi.Models.MDFe", "MDFe")
                        .WithMany("Reboques")
                        .HasForeignKey("MDFeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MDFeApi.Models.Reboque", "Reboque")
                        .WithMany("MDFeReboques")
                        .HasForeignKey("ReboqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MDFe");

                    b.Navigation("Reboque");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeUfPercurso", b =>
                {
                    b.HasOne("MDFeApi.Models.MDFe", "MDFe")
                        .WithMany("UfsPercurso")
                        .HasForeignKey("MDFeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MDFe");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeUnidadeCarga", b =>
                {
                    b.HasOne("MDFeApi.Models.MDFe", "MDFe")
                        .WithMany()
                        .HasForeignKey("MDFeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MDFeApi.Models.MDFeUnidadeTransporte", null)
                        .WithMany("UnidadesCarga")
                        .HasForeignKey("MDFeUnidadeTransporteId");

                    b.Navigation("MDFe");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeUnidadeTransporte", b =>
                {
                    b.HasOne("MDFeApi.Models.MDFeCte", "MDFeCte")
                        .WithMany()
                        .HasForeignKey("MDFeCteId");

                    b.HasOne("MDFeApi.Models.MDFe", "MDFe")
                        .WithMany("UnidadesTransporte")
                        .HasForeignKey("MDFeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MDFeApi.Models.MDFeMdfeTransp", "MDFeMdfeTransp")
                        .WithMany()
                        .HasForeignKey("MDFeMdfeTranspId");

                    b.HasOne("MDFeApi.Models.MDFeNfe", "MDFeNfe")
                        .WithMany()
                        .HasForeignKey("MDFeNfeId");

                    b.Navigation("MDFe");

                    b.Navigation("MDFeCte");

                    b.Navigation("MDFeMdfeTransp");

                    b.Navigation("MDFeNfe");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeValePedagio", b =>
                {
                    b.HasOne("MDFeApi.Models.MDFe", "MDFe")
                        .WithMany("ValesPedagio")
                        .HasForeignKey("MDFeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MDFe");
                });

            modelBuilder.Entity("MDFeApi.Models.Municipio", b =>
                {
                    b.HasOne("MDFeApi.Models.Estado", null)
                        .WithMany("Municipios")
                        .HasForeignKey("EstadoId");
                });

            modelBuilder.Entity("MDFeApi.Models.Usuario", b =>
                {
                    b.HasOne("MDFeApi.Models.Cargo", "Cargo")
                        .WithMany("Usuarios")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("MDFeApi.Models.Cargo", b =>
                {
                    b.Navigation("CargoPermissoes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("MDFeApi.Models.Condutor", b =>
                {
                    b.Navigation("MDFes");
                });

            modelBuilder.Entity("MDFeApi.Models.Contratante", b =>
                {
                    b.Navigation("MDFes");
                });

            modelBuilder.Entity("MDFeApi.Models.Emitente", b =>
                {
                    b.Navigation("MDFes");
                });

            modelBuilder.Entity("MDFeApi.Models.Estado", b =>
                {
                    b.Navigation("Municipios");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFe", b =>
                {
                    b.Navigation("CondutoresAdicionais");

                    b.Navigation("DocumentosCte");

                    b.Navigation("DocumentosMdfeTransp");

                    b.Navigation("DocumentosNfe");

                    b.Navigation("EntregasParciais");

                    b.Navigation("Eventos");

                    b.Navigation("LacresRodoviarios");

                    b.Navigation("LocaisCarregamento");

                    b.Navigation("LocaisDescarregamento");

                    b.Navigation("ProdutosPerigosos");

                    b.Navigation("Reboques");

                    b.Navigation("UfsPercurso");

                    b.Navigation("UnidadesTransporte");

                    b.Navigation("ValesPedagio");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeUnidadeCarga", b =>
                {
                    b.Navigation("LacresUnidadeCarga");
                });

            modelBuilder.Entity("MDFeApi.Models.MDFeUnidadeTransporte", b =>
                {
                    b.Navigation("Lacres");

                    b.Navigation("UnidadesCarga");
                });

            modelBuilder.Entity("MDFeApi.Models.Municipio", b =>
                {
                    b.Navigation("LocaisCarregamento");

                    b.Navigation("LocaisDescarregamento");

                    b.Navigation("MDFesCarregamento");

                    b.Navigation("MDFesCte");

                    b.Navigation("MDFesMdfeTransp");

                    b.Navigation("MDFesNfe");
                });

            modelBuilder.Entity("MDFeApi.Models.Permissao", b =>
                {
                    b.Navigation("CargoPermissoes");
                });

            modelBuilder.Entity("MDFeApi.Models.Reboque", b =>
                {
                    b.Navigation("MDFeReboques");
                });

            modelBuilder.Entity("MDFeApi.Models.Seguradora", b =>
                {
                    b.Navigation("MDFes");
                });

            modelBuilder.Entity("MDFeApi.Models.Veiculo", b =>
                {
                    b.Navigation("MDFes");
                });
#pragma warning restore 612, 618
        }
    }
}
